const CANVAS_FONT_COLOR = '#10f871'
const CANVAS_FONT_RATIO = 0.013

const SIDE_DESKTOP_WIDTH = 260
const SIDE_MOBILE_WIDTH = 200

export {
	CANVAS_FONT_COLOR,
	CANVAS_FONT_RATIO,
	SIDE_DESKTOP_WIDTH,
	SIDE_MOBILE_WIDTH,
}
